### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeviceNotAvailable'

### ISSUE THREAD

**Issue by ngmgit** [tomaka/rodio#130]
I am totally new to rust development and started to learn by picking up this game at https://github.com/thiolliere/ruga and couldnt run it because of this error. Thought this can be a good thing to solve or get to understand rust. I have read the src and i can see the file engine has TODO comment for the `fn new_voice` so i guess its better to post it here.

`
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeviceNotAvailable', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rodio::engine::new_voice
  11: rodio::sink::Sink::new
  12: baal::effect::State::init
  13: baal::init
  14: ruga::init
  15: ruga::main
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  18: __libc_start_main
  19: _start
`

**Comment by ngmgit** [comment]
Can confirm after installing package `pulseaudio-alsa` the game started and there was no unwrap error.
