### ISSUE TITLE
Inexplicable 'UnrecognizedFormat'

### ISSUE THREAD

**Issue by KongouDesu** [tomaka/rodio#139]
I went and got a sound, this particular one [https://freesound.org/people/martian/sounds/403973/](url), however Rodio seems to panic at runtime with an UnrecognizedFormat error.

```rust
extern crate rodio;

use rodio::Sink;
use std::io::BufReader;

fn main() {
    let endpoint = rodio::get_default_endpoint().unwrap();
    let sink = Sink::new(&endpoint);

    let file = std::fs::File::open("403973__martian__beast-whoosh.wav").unwrap();
    let src = rodio::Decoder::new(BufReader::new(file)).unwrap();
    sink.append(src);
    sink.sleep_until_end();
}
```
Results in
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnrecognizedFormat', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0:     0x55e2623ce973 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hcdf51e4c9dc54357
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55e2623cb054 - std::sys_common::backtrace::_print::h9da91fd31a37d0f1
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x55e2623d0a33 - std::panicking::default_hook::{{closure}}::h46820a72bf0cb624
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x55e2623d07a2 - std::panicking::default_hook::h4c1ef1cc83189c8e
                               at /checkout/src/libstd/panicking.rs:396
   4:     0x55e2623d0ef7 - std::panicking::rust_panic_with_hook::h99016f44bdcb8544
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x55e2623d0dc4 - std::panicking::begin_panic_new::hae931f4b9fe56a90
                               at /checkout/src/libstd/panicking.rs:553
   6:     0x55e2623d0cc9 - std::panicking::begin_panic_fmt::h3b8db4524c33692e
                               at /checkout/src/libstd/panicking.rs:521
   7:     0x55e2623d0c5a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:497
   8:     0x55e2623f8d20 - core::panicking::panic_fmt::h955f7c5ec61a82d4
                               at /checkout/src/libcore/panicking.rs:92
   9:     0x55e26227d66b - core::result::unwrap_failed::h5098b88d52d0c498
                               at /checkout/src/libcore/macros.rs:41
  10:     0x55e26225f375 - <core::result::Result<T, E>>::unwrap::ha9ff8a0535b48e3f
                               at /checkout/src/libcore/result.rs:738
  11:     0x55e2622ec26a - rodio_test::main::h00a2b34090bae6e7
                               at src/main.rs:11
  12:     0x55e2623d7e1c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  13:     0x55e2623d162a - std::rt::lang_start::h97aba2334c85f570
                               at /checkout/src/libstd/panicking.rs:458
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:59
  14:     0x55e2622ec362 - main
  15:     0x7f40840f0f69 - __libc_start_main
  16:     0x55e2622352a9 - _start
  17:                0x0 - <unknown>
```
The file plays fine in MPV and other WAV files work aswell.

**Comment by tomaka** [comment]
Chances are that it's a bug in the WAV decoder.

**Comment by ruuda** [comment]
I can reproduce this issue, it is indeed Hound that rejects the file. It appears that the file is nonstandard, but it is possible to make sense of it anyhow. You can follow https://github.com/ruuda/hound/issues/14 for updates. I think I'll have a fix ready soon.

**Comment by Bobo1239** [comment]
@KongouDesu Can this be closed? (https://github.com/ruuda/hound/issues/14 is fixed)
