### ISSUE TITLE
Can we implement `Source::total_duration` for non-wav sources?

### ISSUE THREAD

**Issue by icefoxen** [tomaka/rodio#190]
The question was brought up by this `ggez` issue:  https://github.com/ggez/ggez/issues/477

It does indeed appear to be correct that only the WAV decoder implements this method.  `rodio`'s stream-based API does seem like it might be problematic, but the method only exists when the stream is `Seek`, so I think we can manage it.

Looking at the various upstream crates, does the functionality exist to do this without having to decode the entire stream in the process?

 * `lewton`: https://docs.rs/lewton/0.9.1/lewton/audio/fn.get_decoded_sample_count.html
 * `minimp3`: Doesn't look like it, though I am pretty darn sure that the C library provides the capability to do this.  Just need to write a function that skims through the blocks in the stream reading the metadata without bothering to decode the individual blocks.
 * `claxon`: I think [this](https://docs.rs/claxon/0.4.1/claxon/metadata/struct.StreamInfo.html) has the relevant info, but it doesn't seem reliable (the `samples` field is an `Option`) and I'm not sure if there's a nicer way to get to it

**Comment by ryankopf** [comment]
How is this still an issue?

**Comment by gulis1** [comment]
My application needs `Source::total_duration` implemented for vorbis files. Can I work on a PR to implement this, using the `ogg_metadata` crate?

**Comment by dvdsk** [comment]
hi @gulis good news, we actually have total_duration implemented for the `symphonia` decoders. It should just work. Let me know if it does not!

**Comment by gulis1** [comment]
Hello @dvdsk, ty for answering so fast!!

I'm tried enabling the `symphonia` and `symphonia-all` features, but `rodio::Decoder` returns the following error:
```
thread 'main' panicked at src/main.rs:13:60:
called `Result::unwrap()` on an `Err` value: IoError("end of stream")
```
Without enabling the Symphonia features, the vorbis file (`/assets/music.ogg` from this repo) plays, but `Source::total_duration` does not work.

This is the code I'm using for the test:

```rust
use std::error::Error;
use std::io::BufReader;
use rodio::{OutputStream, Sink};

fn main() -> Result<(), Box<dyn Error>> {

    let (_stream, stream_handle) = OutputStream::try_default()?;
    let sink = Sink::try_new(&stream_handle)?;
       
    let file = std::fs::File::open("assets/music.ogg").unwrap();
    sink.append(rodio::Decoder::new(BufReader::new(file)).unwrap());
    sink.sleep_until_end();

    Ok(())
}
```

And this is the Cargo.toml file:

```toml
[package]
name = "oggtest"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = { version = "0.20.1", features = ["symphonia", "symphonia-all"], default-features = false }
```

This is the first lines Symphonia is logging via the `log` crate:

```
[DEBUG symphonia_core::probe] found a possible format marker within [ff, ff, ff, ff, 0, 71, 2, 0, ff, ff, ff, ff, b8, 1, 4f, 67] @ 0+46 bytes.
[INFO  symphonia_core::probe] found the format marker [ff, ff] @ 0+46 bytes.
[WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[WARN  symphonia_bundle_mp3::demuxer] skipping junk at 54 bytes
[WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[WARN  symphonia_bundle_mp3::demuxer] skipping junk at 19972 bytes
...
```

I've tried various combinations of features, but I haven't managed to get it working. Maybe I'm not understanding properly how they work?

**Comment by gulis1** [comment]
Alright, sorry about the confusion.

I fixed the issue in the previous comment by adding Symphonia to my project's dependencies (is this the intended behaviour?):

**Cargo.toml**
```
[package]
name = "oggtest"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = { version = "0.20.1", features = ["symphonia", "symphonia-all"], default-features=false }
symphonia = "0.5.4"
```

Sadly, even after this `Source::total_duration` doesn't work for me. It looks like the issue is in the `SymphoniaDecoder::init` function (file `/src/decoder/symphonia.rs`), in line 103:

```rust
let total_duration = stream
            .codec_params
            .time_base
            .zip(stream.codec_params.n_frames)               // stream.codec_params.n_frames is None here
            .map(|(base, frames)| base.calc_time(frames));
```

**Comment by dvdsk** [comment]
> I've tried enabling the `symphonia` and `symphonia-all` features, but `rodio::Decoder::new` returns the following error:
> 
> ```
> thread 'main' panicked at src/main.rs:13:60:
> called `Result::unwrap()` on an `Err` value: IoError("end of stream")
> ```

I just wrote a test and you are right! this is not working :(

> I fixed the issue in the previous comment by adding Symphonia to my project's dependencies (is this the intended behaviour?):

Very much not! I'm kinda surprised that worked 😅 

I just remember @roderickvd mentioning making the symphonia decoders more robust (see: https://github.com/RustAudio/rodio/issues/678#issuecomment-2629554670). Maybe that work will fix this too. 

If you would like to have a go at fixing this please go ahead and have fun 👍

**Comment by dvdsk** [comment]
also lets move this to its own issue.

**Comment by roderickvd** [comment]
> I just remember [@roderickvd](https://github.com/roderickvd) mentioning making the symphonia decoders more robust (see: [#678 (comment)](https://github.com/RustAudio/rodio/issues/678#issuecomment-2629554670)). Maybe that work will fix this too.

Yes. Beyond the feature flags, the audio specifications can be `None` for some codecs until the first packet is decoded. So that needs fixing.
