### ISSUE TITLE
Panics when finish playing MP3 on Windows in debug mode

### ISSUE THREAD

**Issue by azriel91** [tomaka/rodio#229]
When playing an mp3 on Windows in debug mode, sometimes `self.next_frame()` is not empty in AAA, leading to this panic:

```
thread 'rodio audio processing' panicked at 'assertion failed: self.next_frame.is_empty()', D:\work\github\tomaka\rodio\src\conversions\sample_rate.rs:193:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Subsequent sounds are no longer played because the `ENGINE` is a static variable and doesn't re-initialize itself.

The line that panics is in `SampleRateConverter`:

https://github.com/tomaka/rodio/blob/92a018bf537a3c571baea1a1084d750416d2249e/src/conversions/sample_rate.rs#L186

`self.next_frame()` is empty `[]` while the sound is playing, but when the sound stops, it had two values, example:

```
// needed to add `Debug` bound in many places
[-0.046173096, -0.046173096]
```

**Stack backtrace**

Note: line numbers may not be accurate because I was munging code to get the information.

```
stack backtrace:
   0: rodio::conversions::sample_rate::{{impl}}::next<rodio::source::uniform::Take<rodio::source::samples_converter::SamplesConverter<rodio::decoder::Decoder<std::io::cursor::Cursor<amethyst_audio::source::Source>>, f32>>> (0x7ff60ca4b213)
             at D:\work\github\tomaka\rodio\src\conversions\sample_rate.rs:188
   1: rodio::conversions::channels::{{impl}}::next<rodio::conversions::sample_rate::SampleRateConverter<rodio::source::uniform::Take<rodio::source::samples_converter::SamplesConverter<rodio::decoder::Decoder<std::io::cursor::Cursor<amethyst_audio::source::Sourc (0x7ff60ca48bec)
             at D:\work\github\tomaka\rodio\src\conversions\channels.rs:62
   2: rodio::conversions::sample::{{impl}}::next<rodio::conversions::channels::ChannelCountConverter<rodio::conversions::sample_rate::SampleRateConverter<rodio::source::uniform::Take<rodio::source::samples_converter::SamplesConverter<rodio::decoder::Decoder<std (0x7ff60ca49203)
             at D:\work\github\tomaka\rodio\src\conversions\sample.rs:38
   3: rodio::source::uniform::{{impl}}::next<rodio::source::samples_converter::SamplesConverter<rodio::decoder::Decoder<std::io::cursor::Cursor<amethyst_audio::source::Source>>, f32>,f32> (0x7ff60ca4fe27)
             at D:\work\github\tomaka\rodio\src\source\uniform.rs:103
   4: alloc::boxed::{{impl}}::next<Source> (0x7ff60dc33ca8)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\liballoc\boxed.rs:668
   5: rodio::dynamic_mixer::{{impl}}::next<f32> (0x7ff60dc3d663)
             at D:\work\github\tomaka\rodio\src\dynamic_mixer.rs:125
   6: rodio::engine::audio_callback (0x7ff60dc2c89c)
             at D:\work\github\tomaka\rodio\src\engine.rs:92
   7: rodio::engine::play_raw::{{impl}}::deref::__static_ref_initialize::{{closure}}::{{closure}} (0x7ff60dc44667)
             at D:\work\github\tomaka\rodio\src\engine.rs:41
   8: cpal::{{impl}}::run::{{closure}}<closure> (0x7ff60dc3c0e8)
             at C:\Users\azrie\.cargo\git\checkouts\cpal-28c60544a02dffaa\0354548\src\lib.rs:495
   9: cpal::cpal_impl::stream::EventLoop::run_inner (0x7ff60dceb2c3)
             at C:\Users\azrie\.cargo\git\checkouts\cpal-28c60544a02dffaa\0354548\src\wasapi\stream.rs:595
  10: cpal::cpal_impl::stream::EventLoop::run<closure> (0x7ff60dc4454e)
             at C:\Users\azrie\.cargo\git\checkouts\cpal-28c60544a02dffaa\0354548\src\wasapi\stream.rs:423
  11: cpal::EventLoop::run<closure> (0x7ff60dc3c047)
             at C:\Users\azrie\.cargo\git\checkouts\cpal-28c60544a02dffaa\0354548\src\lib.rs:495
  12: rodio::engine::play_raw::{{impl}}::deref::__static_ref_initialize::{{closure}} (0x7ff60dc446aa)
             at D:\work\github\tomaka\rodio\src\engine.rs:39
  13: std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()> (0x7ff60dc41d13)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\sys_common\backtrace.rs:137
  14: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure,()> (0x7ff60dc2f283)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\thread\mod.rs:470
  15: std::panic::{{impl}}::call_once<(),closure> (0x7ff60dc41cc3)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\panic.rs:310
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()> (0x7ff60dc44b56)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\panicking.rs:293
  17: panic_unwind::__rust_maybe_catch_panic (0x7ff60e4b18c2)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libpanic_unwind\lib.rs:85
  18: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> (0x7ff60dc44a80)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\panicking.rs:272
  19: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> (0x7ff60dc41ce3)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\panic.rs:388
  20: std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure,()> (0x7ff60dc2f0f3)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libstd\thread\mod.rs:468
  21: core::ops::function::FnOnce::call_once<closure,()> (0x7ff60dc38c13)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\libcore\ops\function.rs:231
  22: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>> (0x7ff60e4958d7)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\src\liballoc\boxed.rs:704
  23: std::sys::windows::thread::{{impl}}::new::thread_start (0x7ff60e4af816)
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641\/src\libstd\sys\windows\thread.rs:47
  24: BaseThreadInitThunk (0x7ffe41f74034)
```

**Comment by tomaka** [comment]
Considering that the user can write a trait implementation that can panic, it wouldn't be a bad idea, in my opinion, to wrap things around a `catch_unwind`.

**Comment by est31** [comment]
Hi #297 has been merged. Could you try out latest master of rodio and check whether the bug still persists?

**Comment by azriel91** [comment]
Heya, I've just tried it, and while it doesn't panic, no audio is played.

**Comment by TimonPost** [comment]
I am getting the same error on Linux. It happens only when I change the pitch especially less than the value 1.0.
