### ISSUE TITLE
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError"...

### ISSUE THREAD

**Issue by Plasticcaz** [tomaka/rodio#71]
Greetings,

When trying to use this library, I end up with an error.

Here is the code that's causing the panic, inspired by one of your examples (https://github.com/tomaka/rodio/blob/master/examples/music_wav.rs)...

```

    use std::io::BufReader;
    let endpoint = rodio::get_default_endpoint().expect("Failed to retrieve default endpoint.");
    let sink = rodio::Sink::new(&endpoint);

    let file = std::fs::File::open(filepath).expect("file missing!");
    let source = rodio::Decoder::new(BufReader::new(file)).unwrap();
    sink.append(source);
    sink.sleep_until_end();


```
This is currently residing in a trigger system, so it currently occurs when the player steps on a particular tile. When I step on that tile, I get the following error:

```

thread '<main>' panicked at 'Unknown SubFormat GUID returned by GetMixFormat: GUID { Data1: 1048576, Data2: 128, Data3: 43520, Data4: [0, 56, 155, 113, 164, 120, 36, 176] }', C:\Users\<USERNAME>\.cargo\registry\src\github.com-88ac128001ac3a9a\cpal-0.2.11\src\wasapi/mod.rs:191
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore\result.rs:746
stack backtrace:
   0:     0x7ff7be789b5b - std::rt::lang_start::h5b0863080165c75e
   1:     0x7ff7be788f5b - std::rt::lang_start::h5b0863080165c75e
   2:     0x7ff7be77d34f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   3:     0x7ff7be77e33d - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   4:     0x7ff7be78456b - rust_begin_unwind
   5:     0x7ff7be78f1b5 - core::panicking::panic_fmt::h73bf9d7e8e891a73
   6:     0x7ff7be66ae6f - main
   7:     0x7ff7be6676a6 - main
   8:     0x7ff7be64f47d - __ImageBase
   9:     0x7ffb3afbc6bb - _C_specific_handler
  10:     0x7ffb50859b7c - _chkstk
  11:     0x7ffb507e595b - RtlUnwindEx
  12:     0x7ffb3afbc604 - _C_specific_handler
  13:     0x7ffb50859afc - _chkstk
  14:     0x7ffb507e4fe8 - RtlImageNtHeaderEx
  15:     0x7ffb507e6c93 - RtlRaiseException
  16:     0x7ffb4cf61f27 - RaiseException
  17:     0x7ff7be782517 - std::io::stdio::_print::h03730948b3f63a9b
  18:     0x7ff7be77d4a9 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
  19:     0x7ff7be77e33d - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
  20:     0x7ff7be777b3c - cpal::cpal_impl::Endpoint::get_supported_formats_list::h49aba8504a03d688
  21:     0x7ff7be7673b7 - rodio::engine::Engine::start::hb7ef03fed4b01782
  22:     0x7ff7be647c3c - __ImageBase
  23:     0x7ff7be788928 - std::rt::lang_start::h5b0863080165c75e
  24:     0x7ff7be7844d8 - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  25:     0x7ff7be7886d7 - std::rt::lang_start::h5b0863080165c75e
  26:     0x7ff7be7af24f - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:255
  27:     0x7ffb4dc08101 - BaseThreadInitThunk
thread panicked while panicking. aborting.
error: Process didn't exit successfully: `target\release\project_zed.exe` (exit code: 3221225477)
```

This panic is occuring lower than the caller level, so I'm not sure there is anything I can do with it at the user level.

Thanks,
Plasticcaz

EDIT: I should probably give some system info too:
I am running Windows 10 64-bit. If you need anything else, please ask.

**Comment by tomaka** [comment]
Thanks for the report.
However this is an issue with cpal, not rodio. Please open an issue there: https://github.com/tomaka/cpal/issues
